name: Reusable Deploy
on: 
  workflow_call: 
    inputs: 
      artifact-name:
        description: Deployable artifacts
        required: false
        default: dist
        type: string
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Upload artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
      - name: list files
        run: ls
      - name: output information
        run: echo "deploying & uploading"