name: Reusable Deploy
on: 
  workflow_call: 
    inputs: 
      artifact-name:
        description: Deployable artifacts
        required: false
        default: dist
        type: string
    # secrets:
    #   some-secrets:   #calling secret for this job
    #     required: false
    outputs:  
      result: #step-3
        description: The result of the deployment operation
        value: ${{ jobs.deploy.outputs.outcome }}
jobs:
  deploy:
    outputs:  #step-2
      outcome: ${{ steps.set-result.outputs.step-result }}
    runs-on: ubuntu-latest
    steps:
      - name: Upload artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
      - name: list files
        run: ls
      - name: output information
        run: echo "deploying & uploading"
      - name: set result output #step-1
        id: set-result
        run: echo "step-result=success" >> $GITHUB_OUTPUT